import { v4 as uuid } from 'uuid';

const referRequests = [
  {
    id: uuid(),
    email: 'anyuany@andrew.cmu.edu',
    phone: '123-456-7890',
    appliedAt: 1554930000000,
    avatarUrl: '/static/images/avatars/avatar_13.png',
    jobTitle: 'Dropbox - Software Engineer',
    jobLink: 'https://www.dropbox.com/jobs/teams/engineering',
    applicantName: 'Anyuan Yu',
    applicantLinkedin: 'https://www.linkedin.com/in/anyuanyu/',
  },
  {
    id: uuid(),
    email: 'dezhiy@andrew.cmu.edu',
    phone: '123-456-7890',
    appliedAt: 1554930000000,
    avatarUrl: '/static/images/avatars/avatar_16.png',
    jobTitle: 'Medium Corporation - Product Manager',
    jobLink: 'https://medium.com/tag/product-management',
    applicantName: 'Dezhi Yu',
    applicantLinkedin: 'https://www.linkedin.com/in/halffrost/',
  },
  {
    id: uuid(),
    email: 'zizhenl@andrew.cmu.edu',
    phone: '123-456-7890',
    appliedAt: 1554930000000,
    avatarUrl: '/static/images/avatars/avatar_17.png',
    jobTitle: 'Slack - Software Engineer',
    jobLink: 'https://slack.com/intl/zh-cn/careers',
    applicantName: 'Zizhen Liu',
    applicantLinkedin: 'https://www.linkedin.com/in/zizhen-liu-869229106/',
  },
  {
    id: uuid(),
    email: 'xiaoxiaoq@andrew.cmu.edu',
    phone: '123-456-7890',
    appliedAt: 1554930000000,
    avatarUrl: '/static/images/avatars/avatar_14.png',
    jobTitle: 'Lyft - APM Program',
    jobLink: 'https://www.lyft.com/careers/apm',
    applicantName: 'Xiaoxiao Qin',
    applicantLinkedin: 'https://www.linkedin.com/in/annie-qin-0127/',
  },
  {
    id: uuid(),
    email: 'kunyil@andrew.cmu.edu',
    phone: '123-456-7890',
    appliedAt: 1554930000000,
    avatarUrl: '/static/images/avatars/avatar_15.png',
    jobTitle: 'GitHub - Businness Strategy',
    jobLink: 'https://boards.greenhouse.io/github',
    applicantName: 'Kunyi Lai',
    applicantLinkedin: 'https://www.linkedin.com/in/lucky559/',
  },
  {
    id: uuid(),
    email: 'anyuany@andrew.cmu.edu',
    phone: '123-456-7890',
    appliedAt: 1554930000000,
    avatarUrl: '/static/images/avatars/avatar_13.png',
    jobTitle: 'Squarespace - Product Designer',
    jobLink: 'https://www.squarespace.com/about/careers',
    applicantName: 'Anyuan Yu',
    applicantLinkedin: 'https://www.linkedin.com/in/anyuanyu/',
  },
];

export default referRequests;
